---
# vim:ft=ansible:

https_health_check:
  name: stretto-https-health-check
  project: nicos-101-project
  port: 8443
  request_path: /stretto/status
  check_interval: 5
  timeout: 5
  unhealthy_threshold: 2
  healthy_threshold: 2

http_health_check:
  name: stretto-http-health-check
  project: nicos-101-project
  port: 8080
  request_path: /stretto/status
  check_interval: 5
  timeout: 5
  unhealthy_threshold: 2
  healthy_threshold: 2

prov_health_check:
  name: stretto-prov-health-check
  project: nicos-101-project
  port: 9200
  request_path: /status
  check_interval: 5
  timeout: 5
  unhealthy_threshold: 2
  healthy_threshold: 2


